<?php declare(strict_types=1); ?>
<?php $this->layout('layout', ['title' => 'Engraving']) ?>

<div class="container">
    <div class="row">
        <div class="column" style="text-align: center">
            <br>
            <a href="https://github.com/mhilker/engraving" target="_blank">
                <img src="/engraving.svg" alt="Engraving">
            </a>
            <h1>Engraving HTTP Application</h1>
        </div>
    </div>
</div>
